### ISSUE TITLE
Wrap code blocks

### ISSUE THREAD

**Issue by vkkodali** [joeyespo/grip#214]
Is there a way to wrap text in the code blocks? I'd appreciate if you can point me to the lines in CSS that need to be changed, I can do that after I export to html.   --Thanks!

**Comment by joeyespo** [comment]
Yeah, this would best be done outside of Grip since GitHub doesn't offer text wrapping in code blocks.

Since all code blocks are `<pre>` elements, you can add [something like this](http://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag):

```css
pre {
    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
```
